### PR TITLE
Take Two: Social Hashtags - Fixed Twitter OAuth, added options

### PR DESCRIPTION
**Pull request by mandiberg**
Hi Bryan, here are the changes made by Team Mandiberg.

You can see the code working here: http://www.artspracticum.org/social/

The full granular commit info is here: https://github.com/mandiberg/social-hashtags (I couldn't get the old fork to point to the new base... so doing it by brute force.)
- Added option to keep or remove hashtagged words in retrieved posts.
- Added functionality to store more metadata from posts retrieved from
  Twitter and Instagram, including:
  - URL to post on Twitter/Instagram
  - URL to user on Twitter/Instagram
  - Timestamp for post from Twitter/Instagram
- Exposed metadata from retrieved posts to be displayed in the archive
  page.
- Added option to keep or remove Emoji from retrieved posts.
- Added option to whitelist usernames.
- Added option to pick a wordpress user to use as the author for
  social-hashtag posts.

### CODE REVIEW

**Comment by shanaver** [comment]
Thanks guys - I'll review and merge it as soon as I can!

**Comment by mandiberg** [comment]
Thanks

Michael

**Comment by mandiberg** [comment]
Hey Shanaver. I wanted to ping you to see if you had any progress on reviewing and merging this code? Thanks. M

**Comment by mandiberg** [comment]
Hi Shanaver, can you please review and merge this code?

**Comment by shanaver** [comment]
mandiberg, sorry for such a late reply - I'll merge & review today - thanks!

**Comment by shanaver** [comment]
mandiberg - if you create a WP.org user, I'll just add you to the SVN repo so you can commit directly:

https://wordpress.org/support/register.php

That way you won't have to wait for me in the future :)

**Comment by mandiberg** [comment]
Hi Bryan

Sorry for the long radio silence. I was working on this:
http://www.nytimes.com/2015/06/17/books/moving-wikipedia-from-computer-to-many-many-bookshelves.html

I have some updates for Social Hashtag. My WP.org user is "mandiberg" -- if
you add me to the SVN repo, I will commit directly

TX

Michael

ᐧ

**Comment by mandiberg** [comment]
Hi Bryan

Any chance you can give me commit perms on the SVN so I can update Social
Hashtags directly on WP?

My WP.org user is "mandiberg"

m

**Pull request merged**
